-- ============================================================
-- THIS MIGRATION HAS BEEN DISABLED
-- ============================================================
-- It previously inserted dummy/fake price history and DELETED
-- real price history data. This caused incorrect price-drop
-- alerts because the stored prices did not reflect reality.
--
-- All price history is now populated exclusively by the cron
-- job and the addProduct action — no fake data.
-- ============================================================
